import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/contexts/theme-provider";
import Header from "./components/Header";
import Gradient from "./components/Gradient";

const font = Montserrat({
    subsets: ["latin"],
    weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={`${font.className} antialiased`}>
                <ThemeProvider>
                    <Header />
                    <Gradient />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
